package dev.d4nilpzz.utils;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

public class MavenUtils {

    public static String generatePom(String groupId, String artifactId, String version) {
        return """
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>%s</groupId>
                  <artifactId>%s</artifactId>
                  <version>%s</version>
                  <description>POM was generated by Repossify</description>
                </project>
                """.formatted(groupId, artifactId, version).trim();
    }

    public static String generateMavenMetadata(String groupId, String artifactId, Set<String> versions) {
        List<String> sorted = versions.stream()
                .sorted(MavenUtils::compareSemver)
                .toList();

        String latest = sorted.isEmpty() ? "" : sorted.getLast();

        // release = latest non-snapshot
        String release = sorted.stream()
                .filter(v -> !v.endsWith("-SNAPSHOT"))
                .reduce("", (a, b) -> b);

        String lastUpdated = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));

        StringBuilder versionsXml = new StringBuilder();
        for (String v : sorted) {
            versionsXml.append("      <version>").append(v).append("</version>\n");
        }

        return """
                <metadata>
                  <groupId>%s</groupId>
                  <artifactId>%s</artifactId>
                  <versioning>
                    <release>%s</release>
                    <latest>%s</latest>
                    <versions>
                %s    </versions>
                    <lastUpdated>%s</lastUpdated>
                  </versioning>
                </metadata>
                """.formatted(groupId, artifactId, release, latest, versionsXml, lastUpdated).trim();
    }

    public static String generateSnapshotMetadata(
            String groupId, String artifactId, String version,
            String timestamp, int buildNumber) {

        String lastUpdated = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));

        String snapshotVersion = version.replace("SNAPSHOT", timestamp + "-" + buildNumber);

        return """
                <metadata>
                  <groupId>%s</groupId>
                  <artifactId>%s</artifactId>
                  <version>%s</version>
                  <versioning>
                    <snapshot>
                      <timestamp>%s</timestamp>
                      <buildNumber>%d</buildNumber>
                    </snapshot>
                    <lastUpdated>%s</lastUpdated>
                    <snapshotVersions>
                      <snapshotVersion>
                        <extension>jar</extension>
                        <value>%s</value>
                        <updated>%s</updated>
                      </snapshotVersion>
                      <snapshotVersion>
                        <extension>pom</extension>
                        <value>%s</value>
                        <updated>%s</updated>
                      </snapshotVersion>
                    </snapshotVersions>
                  </versioning>
                </metadata>
                """.formatted(
                groupId, artifactId, version,
                timestamp, buildNumber,
                lastUpdated,
                snapshotVersion, lastUpdated,
                snapshotVersion, lastUpdated
        ).trim();
    }

    /**
     * Compares Maven version strings with proper numeric ordering.
     * Handles SNAPSHOT suffix (always sorts last within same base version).
     */
    public static int compareSemver(String a, String b) {
        boolean aSnap = a.endsWith("-SNAPSHOT");
        boolean bSnap = b.endsWith("-SNAPSHOT");
        String aBase = aSnap ? a.substring(0, a.length() - 9) : a;
        String bBase = bSnap ? b.substring(0, b.length() - 9) : b;

        String[] aParts = aBase.split("[.\\-]");
        String[] bParts = bBase.split("[.\\-]");

        int len = Math.max(aParts.length, bParts.length);
        for (int i = 0; i < len; i++) {
            String ap = i < aParts.length ? aParts[i] : "0";
            String bp = i < bParts.length ? bParts[i] : "0";
            int cmp = compareVersionPart(ap, bp);
            if (cmp != 0) return cmp;
        }

        // Same base version: SNAPSHOT is "older" than release
        if (aSnap && !bSnap) return -1;
        if (!aSnap && bSnap) return 1;
        return 0;
    }

    private static int compareVersionPart(String a, String b) {
        try {
            return Integer.compare(Integer.parseInt(a), Integer.parseInt(b));
        } catch (NumberFormatException e) {
            return a.compareToIgnoreCase(b);
        }
    }
}
