package dev.d4nilpzz.utils;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Set;
import java.util.TreeSet;

public class MavenUtils {

    public static String generatePom(String groupId, String artifactId, String version) {
        return """
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>%s</groupId>
          <artifactId>%s</artifactId>
          <version>%s</version>
          <description>POM was generated by Reposilite</description>
        </project>
        """.formatted(groupId, artifactId, version).trim();
    }

    public static String generateMavenMetadata(
            String groupId,
            String artifactId,
            Set<String> versions
    ) {
        String latest = versions.stream().max(String::compareTo).orElse("");
        String lastUpdated = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));

        StringBuilder versionsXml = new StringBuilder();
        for (String v : versions) {
            versionsXml.append("<version>").append(v).append("</version>");
        }

        return """
        <metadata>
          <groupId>%s</groupId>
          <artifactId>%s</artifactId>
          <version/>
          <versioning>
            <release>%s</release>
            <latest>%s</latest>
            <snapshot>
              <timestamp/>
              <buildNumber/>
              <localCopy/>
            </snapshot>
            <lastUpdated>%s</lastUpdated>
            <versions>
              %s
            </versions>
          </versioning>
        </metadata>
        """
                .formatted(groupId, artifactId, latest, latest, lastUpdated, versionsXml)
                .trim();
    }

    public static Set<String> mergeVersions(Set<String> existing, String newVersion) {
        Set<String> out = new TreeSet<>(existing);
        out.add(newVersion);
        return out;
    }
}
