package dev.d4nilpzz.utils;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

public final class MavenUtils {

    private MavenUtils() {
    }

    /**
     * Minimal POM for an artifact uploaded without one.
     * <p>
     * This is only ever written when a dashboard upload explicitly asks for it. It is
     * deliberately <em>not</em> produced during a {@code PUT} deploy: a generated POM
     * declares no dependencies, so a consumer resolves it, compiles fine, and then fails at
     * runtime with {@code NoClassDefFoundError}.
     */
    public static String generatePom(String groupId, String artifactId, String version) {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>%s</groupId>
                  <artifactId>%s</artifactId>
                  <version>%s</version>
                  <description>POM generated by Repossify; it declares no dependencies.</description>
                </project>
                """.formatted(groupId, artifactId, version).trim();
    }

    /**
     * Orders Maven versions: numeric segments compare numerically, and a trailing qualifier
     * orders before the plain release it qualifies, so {@code 1.0-rc1} precedes {@code 1.0}
     * and {@code 1.10} outranks {@code 1.9}.
     */
    public static int compareVersions(String first, String second) {
        List<Object> left = tokenize(first);
        List<Object> right = tokenize(second);

        int size = Math.max(left.size(), right.size());
        for (int i = 0; i < size; i++) {
            Object a = i < left.size() ? left.get(i) : null;
            Object b = i < right.size() ? right.get(i) : null;

            int comparison = compareTokens(a, b);
            if (comparison != 0) return comparison;
        }
        return 0;
    }

    public static Comparator<String> versionComparator() {
        return MavenUtils::compareVersions;
    }

    private static int compareTokens(Object a, Object b) {
        if (a == null && b == null) return 0;

        // A missing segment counts as 0 against a number and as a plain release against a qualifier.
        if (a == null) return b instanceof Integer number ? Integer.compare(0, number) : -qualifierOrder(b);
        if (b == null) return a instanceof Integer number ? Integer.compare(number, 0) : qualifierOrder(a);

        if (a instanceof Integer first && b instanceof Integer second) return Integer.compare(first, second);
        if (a instanceof Integer) return 1;   // a numeric segment outranks a qualifier
        if (b instanceof Integer) return -1;

        int order = Integer.compare(qualifierOrder(a), qualifierOrder(b));
        if (order != 0) return order;
        return ((String) a).compareToIgnoreCase((String) b);
    }

    /**
     * Relative rank of a textual qualifier. Anything unrecognised sorts just below a plain
     * release so an unknown suffix never outranks the final version.
     */
    private static int qualifierOrder(Object token) {
        if (token == null) return 0;
        return switch (token.toString().toLowerCase(Locale.ROOT)) {
            case "alpha", "a" -> -6;
            case "beta", "b" -> -5;
            case "milestone", "m" -> -4;
            case "rc", "cr" -> -3;
            case "snapshot" -> -2;
            case "ga", "final", "release" -> 0;
            case "sp" -> 1;
            default -> -1;
        };
    }

    /** Splits a version into numeric and textual tokens: {@code 1.0-rc2} becomes [1, 0, "rc", 2]. */
    private static List<Object> tokenize(String version) {
        List<Object> tokens = new ArrayList<>();
        if (version == null || version.isEmpty()) return tokens;

        StringBuilder buffer = new StringBuilder();
        Boolean bufferIsDigits = null;

        for (int i = 0; i < version.length(); i++) {
            char c = version.charAt(i);

            if (c == '.' || c == '-' || c == '_') {
                flush(tokens, buffer, bufferIsDigits);
                bufferIsDigits = null;
                continue;
            }

            boolean isDigit = Character.isDigit(c);
            if (bufferIsDigits != null && bufferIsDigits != isDigit) {
                // A digit/letter boundary starts a new token: "rc2" becomes "rc" then 2.
                flush(tokens, buffer, bufferIsDigits);
            }
            bufferIsDigits = isDigit;
            buffer.append(c);
        }
        flush(tokens, buffer, bufferIsDigits);
        return tokens;
    }

    private static void flush(List<Object> tokens, StringBuilder buffer, Boolean isDigits) {
        if (buffer.isEmpty()) return;
        String value = buffer.toString();
        buffer.setLength(0);

        if (Boolean.TRUE.equals(isDigits)) {
            try {
                tokens.add(Integer.parseInt(value));
                return;
            } catch (NumberFormatException ignored) {
                // Absurdly long numeric run; keep it as text.
            }
        }
        tokens.add(value);
    }
}
